# Generated by Django 3.1.3 on 2020-11-18 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='system_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_img', models.ImageField(upload_to='personates')),
                ('nome1', models.CharField(max_length=100)),
                ('nome2', models.CharField(max_length=100)),
                ('nome3', models.CharField(max_length=100)),
                ('difficulty', models.IntegerField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_images',
            },
        ),
        migrations.CreateModel(
            name='points_x_system',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('points', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'points_x_system',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chal_win', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='games_created',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=500)),
                ('url_img1', models.ImageField(upload_to='personates')),
                ('url_img2', models.ImageField(upload_to='personates')),
                ('url_img3', models.ImageField(upload_to='personates')),
                ('nome1_img1', models.TextField()),
                ('nome2_img1', models.TextField()),
                ('nome3_img1', models.TextField()),
                ('nome1_img2', models.TextField()),
                ('nome2_img2', models.TextField()),
                ('nome3_img2', models.TextField()),
                ('nome1_img3', models.TextField()),
                ('nome2_img3', models.TextField()),
                ('nome3_img3', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'games_created',
            },
        ),
        migrations.CreateModel(
            name='Challanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challanger_points', models.CharField(max_length=5000)),
                ('challanged_points', models.CharField(max_length=5000)),
                ('challanger_finish', models.BooleanField(default=False)),
                ('challanged_finish', models.BooleanField(default=False)),
                ('challanged_accepted', models.BooleanField(default=False)),
                ('challanged_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challanged_id', to=settings.AUTH_USER_MODEL)),
                ('challanger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challanger_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Challanges',
            },
        ),
    ]
