# Generated by Django 3.1.3 on 2020-11-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challanges',
            name='challanged_accepted',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='challanges',
            name='challanged_points',
            field=models.CharField(default=0, max_length=5000),
        ),
        migrations.AlterField(
            model_name='challanges',
            name='challanger_points',
            field=models.CharField(default=0, max_length=5000),
        ),
    ]
