# Generated by Django 3.1.3 on 2020-11-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201119_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='games_created',
            name='nome_certo_img1',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='games_created',
            name='nome_certo_img2',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='games_created',
            name='nome_certo_img3',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='system_images',
            name='nome_certo',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
