# Generated by Django 3.1.3 on 2020-11-15 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20201115_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challanger_points', models.CharField(max_length=5000)),
                ('challanged_points', models.CharField(max_length=5000)),
                ('challanger_finish', models.BooleanField(default=False)),
                ('challanged_finish', models.BooleanField(default=False)),
                ('challanged_accepted', models.BooleanField(default=False)),
                ('challanged_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challanged_id', to=settings.AUTH_USER_MODEL)),
                ('challanger_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challanger_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Challanges',
            },
        ),
    ]
