# Generated by Django 3.1.3 on 2020-11-15 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_system_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='games_created',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=500)),
                ('url_img1', models.ImageField(upload_to='')),
                ('url_img2', models.ImageField(upload_to='')),
                ('url_img3', models.ImageField(upload_to='')),
                ('nome1_img1', models.TextField()),
                ('nome2_img1', models.TextField()),
                ('nome3_img1', models.TextField()),
                ('nome1_img2', models.TextField()),
                ('nome2_img2', models.TextField()),
                ('nome3_img2', models.TextField()),
                ('nome1_img3', models.TextField()),
                ('nome2_img3', models.TextField()),
                ('nome3_img3', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'games_created',
            },
        ),
    ]
