# Generated by Django 3.1.3 on 2020-11-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_games_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games_created',
            name='url_img1',
            field=models.ImageField(upload_to='personates'),
        ),
        migrations.AlterField(
            model_name='games_created',
            name='url_img2',
            field=models.ImageField(upload_to='personates'),
        ),
        migrations.AlterField(
            model_name='games_created',
            name='url_img3',
            field=models.ImageField(upload_to='personates'),
        ),
        migrations.AlterField(
            model_name='points_x_system',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='system_images',
            name='url_img',
            field=models.ImageField(upload_to='personates'),
        ),
    ]
